### PR TITLE
Override requirements

### LINKED ISSUE #12: No method for substituting a course with another to fulfill requirements

### PR DESCRIPTION
**Pull request by liuric**
Resolves #12 
Adds menu to course cells for requirements, dialog for substituting other courses.

### CODE REVIEW

**Review by venkatesh-sivaraman — COMMENTED** [review]
Looks awesome! Some general feedback:
* The current implementation of ignore actually fulfills the requirement, whereas it should force it to be unfulfilled
* The name of the ignored requirement should be shown on the course tile below the "Ignored" heading
* For manual progress tiles (see Additional EECS under major6-3 for an example), we should stop showing the manual progress dialog and instead show the substitution dialog.

Other nitpicks:
* In the popup menu, the convention in other parts of the app is to use sentence case (first word capitalized, other words uncapitalized). Also, maybe "undo ignore" should be "don't ignore", since it's not necessarily the last thing the user did.
* The dialog to choose substitutions looks great! A couple nitpicks:
  * Can the list of subjects go all the way to the left and right edges of the dialog? It will make more space and look a little more balanced.
* When you hit Don't Override, the dialog shouldn't be shown again
* linearlayout_course.xml: line 101 should be `android:layout_alignParentEnd="true"`

**Comment by liuric** [comment]
So I changed Ignore to leave it unfulfilled, but would a better implementation be to try to remove the course itself from consideration during the fulfillment calculation? (e.g. you would have to fulfill 4 requirements instead of 5 if u ignored the 5th)

Additionally, I was wondering if we should be referring to the substitution system as solely "override" or "substitute", since the dialog/menu items currently refer to it as "overrides" but the course cell header refers to it as "substituted".

**Comment by venkatesh-sivaraman** [comment]
This looks really good - fantastic work. Only thing I would say about the UI now is to try to adjust the text margins so that the left edge of the dialog title and the semester headers both line up with the select course cells' text.

That's a great point I didn't think about before - it makes sense that the "ignore" option should completely remove the requirement from consideration. When we loop over the child requirements and compute their status (`RequirementsListStatement.java:739`), we should probably just skip the rest of the loop body if the child is ignored.

Related to that point, there's a somewhat weird behavior when I try to ignore the 6.UAT requirement in major6-3. If I ignore 6.UAT and add 6.UAR to my road, the parent requirement doesn't show up as fulfilled. But for some reason, if I flip it around - ignore 6.UAR and add 6.UAT to my road - it does fulfill the parent. Once you implement the suggestion about removing the ignored requirement from counting at all, we should investigate if this is still occurring.

Re terminology, I think either "override" or "substitute" works, but we should be consistent. I'd slightly prefer "substitute" because while "ignore" is also an override, this button is specifically allowing you to make a substitution.

**Comment by venkatesh-sivaraman** [comment]
Something similar to [this change on the backend server](https://github.com/venkatesh-sivaraman/fireroad-server/commit/29fb96579ee68acfa2a98ec96d55cd898e6f7ab0) ought to do the trick.

**Comment by venkatesh-sivaraman** [comment]
LGTM - I think we should go ahead and merge.

**Pull request merged**
